manifest:
  remotes:
    - name: zmkfirmware
      #url-base: https://github.com/zmkfirmware
      url-base: https://github.com/ftc
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
