manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware/zmk/pull/1853
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
